## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('bridge', ['network'])
    obj.source = [
        'model/buf_bridge-net-device.cc',
        'model/bridge-net-device.cc',
        'model/bridge-channel.cc',
        'helper/bridge-helper.cc',
        'helper/buf_bridge-helper.cc'
        ]
    headers = bld(features='ns3header')
    headers.module = 'bridge'
    headers.source = [
        'model/buf_bridge-net-device.h',
        'model/bridge-net-device.h',
        'model/bridge-channel.h',
        'helper/bridge-helper.h',
        'helper/buf_bridge-helper.h'
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
